name: Test

on: [push]

jobs:
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go toolchain
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Test
      run: go test -v ./...

    - name: Test -race
      run: go test -v -race ./...
